services:
  db:
    image: postgres:15
    container_name: loganalyzer_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: loganalyzer
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./my-app-backend
    container_name: loganalyzer_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://appuser:secretpassword@db:5432/loganalyzer
      - JWT_SECRET=your_jwt_secret_here
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./soc-dashboard
    container_name: loganalyzer_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data: